name: Publish Classic UI

on:
  push:
    branches:
      - classic

jobs:
  publish-classic:
    runs-on: ubuntu-latest
    steps:
      - name: Allow setting envs
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          ref: classic
          fetch-depth: 0

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: install dependencies
        run: |
          npm install --global yarn
          yarn

      - name: graphql codegen (classic schema)
        env:
          NEXT_PUBLIC_BASE_URL: ${{ secrets.CLASSIC_API_URL }}
        run: |
          yarn generate

      - name: build project for /classic
        env:
          # Ensure the built app uses relative paths under /classic
          NEXT_PUBLIC_BASE_URL: ""
          NEXT_PUBLIC_BASE_PATH: /classic
          NEXT_PUBLIC_API_PATH: /graphql
          NEXT_PUBLIC_SOCKET_PATH: /classic/socket.io
        run: |
          yarn build
          touch out/.nojekyll

      - name: Deploy classic to gh-pages/classic ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: out
          target-folder: classic
          clean: true
